# Generated by Django 5.1.1 on 2024-11-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_stock_high_price_stock_low_price_stock_open_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
