# Generated by Django 5.1.1 on 2024-11-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_transaction_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='graphs',
            field=models.ImageField(default='stock/media/profile_pictures/graph.jpg', upload_to='static/stock/media/graphs/'),
        ),
    ]
