# Generated by Django 5.1.1 on 2024-11-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_portfolio_graphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='graphs',
            field=models.ImageField(default='static/stock/media/graphs/graph.jpg', upload_to='static/stock/media/graphs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/stock/media/profile_pictures/profile.jpg', upload_to='static/stock/media/profile_pictures/'),
        ),
    ]
