# Generated by Django 5.1.1 on 2024-11-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_portfolio_graphs_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='graphs',
            field=models.ImageField(default='static/stock/graphs/graph.jpg', upload_to='static/stock/graphs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/stock/profile_pictures/profile.jpg', upload_to='static/stock/profile_pictures/'),
        ),
    ]
