# Generated by Django 5.1.1 on 2024-11-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(default='static/stock/stock_graph/default.jpg', upload_to='static/stock/stock_graph/'),
        ),
    ]
